title: "Valhalla's 13th"
url: "https://valhallainnovations.net"
baseurl: ""
remote_theme: daattali/beautiful-jekyll@master

# Essential for your custom styles
css: ["/assets/css/custom.css"]

# Kill the theme's interference
show_theme_link: false
show_github_footer: false
bigimg: []
